# Source files
root=$HOME
source $root/.exports         # Various exports
source $root/.aliases         # User-defined aliases
source $root/.aliases.local   # Extra aliases
source $root/.secrets.local   # Secrets

HISTSIZE=
HISTFILESIZE=
SHELL_SESSION_HISTORY=0
